/**
 * The pure fold: step(data, state, action) -> state.
 *
 * Wave-3 turn shape (one turn = one quarter):
 *   upkeep (on advance, both seats) -> USA: allocate -> policy -> event ->
 *   CHINA: allocate -> policy -> event -> ONE world update -> report -> advance
 *
 * Two seats, one world. Card data is seat-agnostic: plain effect targets hit
 * the acting seat, 'rival.*' targets hit the other seat, 'rival.trust' hits
 * the shared bilateral trust. In solo mode the scripted seat's actions are
 * generated by a driver (engine/china-policy.ts) and RECORDED, so solo and
 * hotseat replay as the same pure fold.
 *
 * Everything here is exact integer math over cloned plain state. Illegal
 * actions throw EngineError with a code; the UI renders from legalActions()
 * and never guesses.
 */
import type { EngineData } from './data';
import { clamp, divRound, evalCurve, mulDiv } from './math';
import { drawFromStream, nextInt, nextIntInRange, weightedIndex } from './rng';
import type {
  ChoiceEventData,
  EffectSetData,
  FixedEventData,
  ParametersData,
  PolicyCardData,
  SeatRulesData,
  WildcardEventData,
} from './schemas';
import type {
  Action,
  ActionType,
  EffectTarget,
  EraId,
  GameState,
  LogEntry,
  Phase,
  PlayableSeatId,
  RivalPosture,
  RngStreamName,
  SeatState,
} from './types';
import {
  ALLOCATION_TOTAL,
  PLAYABLE_SEAT_IDS,
  SCALE_MAX,
  SCALE_MIN,
  WORLD_FLAGS,
  otherSeat,
} from './types';

/** Allocation cap on the capability share during a forced pause (incident fallout). */
export const FORCED_PAUSE_CAPABILITY_MAX = 30;

const WORLD_FLAG_SET: ReadonlySet<string> = new Set(WORLD_FLAGS);

export class EngineError extends Error {
  readonly code:
    | 'runEnded'
    | 'wrongPhase'
    | 'wrongSeat'
    | 'badAllocation'
    | 'unknownPolicy'
    | 'policyNotInHand'
    | 'policyGated'
    | 'policyUnaffordable'
    | 'wrongEvent'
    | 'badChoice';
  constructor(code: EngineError['code'], message: string) {
    super(message);
    this.code = code;
  }
}

// ---------------------------------------------------------------------------
// Legality
// ---------------------------------------------------------------------------

const LEGAL: Record<Phase, ActionType[]> = {
  allocate: ['allocate'],
  policy: ['playPolicy', 'skipPolicy'],
  event: ['resolveEventChoice'],
  report: ['advance'],
  ended: [],
};

export function legalActions(state: GameState): ActionType[] {
  return LEGAL[state.phase];
}

/** Deep-clone plain JSON state (no classes, no Dates: structuredClone is safe). */
function clone(state: GameState): GameState {
  return structuredClone(state);
}

function pushLog(
  state: GameState,
  seat: PlayableSeatId | null,
  entry: Omit<LogEntry, 'turn' | 'seat'>,
): void {
  state.log.push({ turn: state.turn, seat, ...entry });
}

// ---------------------------------------------------------------------------
// Seats, flags and seat-relative effects
// ---------------------------------------------------------------------------

function seatRules(data: EngineData, seat: PlayableSeatId): SeatRulesData {
  return data.seatsRules[seat];
}

/** The flag view a seat's conditions read: its own flags plus world flags. */
function flagsView(state: GameState, seat: PlayableSeatId): ReadonlySet<string> {
  return new Set([...state.world.flags, ...state.seats[seat].flags]);
}

function setFlagFor(state: GameState, seat: PlayableSeatId, flag: string): void {
  if (WORLD_FLAG_SET.has(flag)) {
    if (!state.world.flags.includes(flag)) {
      state.world.flags = [...state.world.flags, flag].sort();
    }
    return;
  }
  const seatState = state.seats[seat];
  if (!seatState.flags.includes(flag)) {
    seatState.flags = [...seatState.flags, flag].sort();
  }
}

function clearFlagFor(state: GameState, seat: PlayableSeatId, flag: string): void {
  if (WORLD_FLAG_SET.has(flag)) {
    state.world.flags = state.world.flags.filter((f) => f !== flag);
    return;
  }
  const seatState = state.seats[seat];
  seatState.flags = seatState.flags.filter((f) => f !== flag);
}

const RESOURCE_TARGETS = new Set([
  'compute',
  'energy',
  'talent',
  'capital',
  'publicTrust',
  'politicalCapital',
  'capability',
  'safetyInsight',
]);

/** Apply one delta, seat-relative. Returns the clamped amount actually applied. */
function applyDelta(
  state: GameState,
  seat: PlayableSeatId,
  target: EffectTarget,
  delta: number,
): number {
  const apply = (current: number): number => clamp(current + delta, SCALE_MIN, SCALE_MAX);
  const own = state.seats[seat];
  const rival = state.seats[otherSeat(seat)];
  if (RESOURCE_TARGETS.has(target)) {
    const key = target as keyof SeatState['resources'];
    const before = own.resources[key];
    own.resources[key] = apply(before);
    return own.resources[key] - before;
  }
  switch (target) {
    case 'society.jobDisplacement': {
      const before = own.society.jobDisplacement;
      own.society.jobDisplacement = apply(before);
      return own.society.jobDisplacement - before;
    }
    case 'society.unrest': {
      const before = own.society.unrest;
      own.society.unrest = apply(before);
      return own.society.unrest - before;
    }
    case 'substitution': {
      const before = own.substitution;
      own.substitution = apply(before);
      return own.substitution - before;
    }
    case 'rival.trust': {
      const before = state.world.bilateralTrust;
      state.world.bilateralTrust = apply(before);
      return state.world.bilateralTrust - before;
    }
    case 'rival.capability': {
      const before = rival.resources.capability;
      rival.resources.capability = apply(before);
      return rival.resources.capability - before;
    }
    case 'rival.substitution': {
      const before = rival.substitution;
      rival.substitution = apply(before);
      return rival.substitution - before;
    }
    case 'hidden.trueAlignment': {
      const before = own.hidden.trueAlignment;
      own.hidden.trueAlignment = apply(before);
      return own.hidden.trueAlignment - before;
    }
    case 'hidden.agencyErosion': {
      const before = own.hidden.agencyErosion;
      own.hidden.agencyErosion = apply(before);
      return own.hidden.agencyErosion - before;
    }
    default:
      throw new EngineError('badChoice', `unknown effect target '${target}'`);
  }
}

function applyEffects(
  state: GameState,
  seat: PlayableSeatId,
  effects: EffectSetData,
  logKind: LogEntry['kind'],
  meta: Record<string, string | number | boolean>,
): void {
  const deltas: Partial<Record<EffectTarget, number>> = {};
  for (const [key, value] of Object.entries(effects)) {
    if (key === 'flags') {
      for (const flag of value as string[]) {
        setFlagFor(state, seat, flag);
      }
      continue;
    }
    if (key === 'clearFlags') {
      for (const flag of value as string[]) {
        clearFlagFor(state, seat, flag);
      }
      continue;
    }
    if (typeof value === 'number') {
      const applied = applyDelta(state, seat, key as EffectTarget, value);
      if (applied !== 0) {
        deltas[key as EffectTarget] = applied;
      }
    }
  }
  pushLog(state, seat, { kind: logKind, stringKey: null, deltas, meta });
}

function queueDelayed(
  state: GameState,
  seat: PlayableSeatId,
  spec: Array<{ inTurns: number; effects: EffectSetData }> | undefined,
  sourceKind: 'event' | 'policy',
  sourceId: string,
  choiceIndex: number | null,
): void {
  for (const delayed of spec ?? []) {
    state.seats[seat].delayed.push({
      dueTurn: state.turn + delayed.inTurns,
      effects: delayed.effects as SeatState['delayed'][number]['effects'],
      sourceKind,
      sourceId,
      choiceIndex,
    });
  }
}

/**
 * The old rival postures survive as READINGS of the shared relationship:
 * cautious at treaty-grade trust, race at rock bottom, mirror between.
 * Thresholds are the sourced posture-check parameters, unchanged.
 */
export function postureFromTrust(parameters: ParametersData, trust: number): RivalPosture {
  if (trust >= parameters.worldRules.postureChecks.cautiousTrustMin.value) {
    return 'cautious';
  }
  if (trust <= parameters.worldRules.postureChecks.raceTrustMax.value) {
    return 'race';
  }
  return 'mirror';
}

// ---------------------------------------------------------------------------
// Mandates (per seat)
// ---------------------------------------------------------------------------

function readVisibleTarget(state: GameState, seat: PlayableSeatId, target: EffectTarget): number {
  const own = state.seats[seat];
  if (RESOURCE_TARGETS.has(target)) {
    return own.resources[target as keyof SeatState['resources']];
  }
  switch (target) {
    case 'society.jobDisplacement':
      return own.society.jobDisplacement;
    case 'society.unrest':
      return own.society.unrest;
    case 'substitution':
      return own.substitution;
    case 'rival.trust':
      return state.world.bilateralTrust;
    case 'rival.capability':
      return state.seats[otherSeat(seat)].resources.capability;
    case 'rival.substitution':
      return state.seats[otherSeat(seat)].substitution;
    default:
      throw new EngineError('badChoice', `mandate goal cannot read '${target}'`);
  }
}

function mandateStream(seat: PlayableSeatId): RngStreamName {
  return seat === 'usa' ? 'mandatesUsa' : 'mandatesChina';
}

/** Assign this era's mandates for one seat (seat-filtered pool, own stream). */
export function assignEraMandates(
  data: EngineData,
  state: GameState,
  seat: PlayableSeatId,
  era: EraId,
): void {
  const seatState = state.seats[seat];
  const assigned = new Set(seatState.mandates.map((m) => m.id));
  const pool = data.mandates.mandates
    .filter((m) => m.era === era && !assigned.has(m.id))
    .filter((m) => (m.seats ? m.seats.includes(seat) : true))
    .sort((a, b) => (a.id < b.id ? -1 : 1));
  const stream = mandateStream(seat);
  for (let n = 0; n < data.mandates.perEraDraw && pool.length > 0; n += 1) {
    const [index, nextRng] = nextInt(state.rng[stream], pool.length);
    state.rng = { ...state.rng, [stream]: [...nextRng] as [number, number, number, number] };
    const chosen = pool.splice(index, 1)[0]!;
    const deadlineTurn = state.turn + chosen.goal.byTurnOffset;
    seatState.mandates = [
      ...seatState.mandates,
      { id: chosen.id, assignedTurn: state.turn, deadlineTurn, status: 'active' },
    ];
    pushLog(state, seat, {
      kind: 'mandate',
      stringKey: chosen.title,
      deltas: null,
      meta: { mandateId: chosen.id, outcome: 'assigned', deadlineTurn },
    });
  }
}

/**
 * Resolve one seat's active mandates. '>=' goals count as met the moment
 * they are reached; '<=' goals must HOLD when the deadline check runs.
 */
function checkMandates(data: EngineData, state: GameState, seat: PlayableSeatId): void {
  const seatState = state.seats[seat];
  for (const mandate of seatState.mandates) {
    if (mandate.status !== 'active') {
      continue;
    }
    const def = data.mandates.mandates.find((m) => m.id === mandate.id)!;
    const current = readVisibleTarget(state, seat, def.goal.target);
    const holds =
      def.goal.comparator === '>=' ? current >= def.goal.value : current <= def.goal.value;
    const atDeadline = state.turn >= mandate.deadlineTurn;
    const deliver = (): void => {
      mandate.status = 'met';
      const applied = applyDelta(state, seat, 'politicalCapital', def.rewardPoliticalCapital);
      pushLog(state, seat, {
        kind: 'mandate',
        stringKey: def.title,
        deltas: applied !== 0 ? { politicalCapital: applied } : {},
        meta: { mandateId: def.id, outcome: 'met', value: current },
      });
    };
    if (def.goal.comparator === '>=' && holds) {
      deliver();
      continue;
    }
    if (!atDeadline) {
      continue;
    }
    if (holds) {
      deliver();
      continue;
    }
    mandate.status = 'lapsed';
    const deltas: Partial<Record<EffectTarget, number>> = {};
    for (const [key, value] of Object.entries(def.penaltyOnLapse ?? {})) {
      if (key === 'flags') {
        for (const flag of value as string[]) {
          setFlagFor(state, seat, flag);
        }
        continue;
      }
      if (typeof value === 'number') {
        const applied = applyDelta(state, seat, key as EffectTarget, value);
        if (applied !== 0) {
          deltas[key as EffectTarget] = applied;
        }
      }
    }
    pushLog(state, seat, {
      kind: 'mandate',
      stringKey: def.title,
      deltas,
      meta: { mandateId: def.id, outcome: 'lapsed', value: current },
    });
  }
}

// ---------------------------------------------------------------------------
// Era
// ---------------------------------------------------------------------------

export function eraForTurn(parameters: ParametersData, turn: number): EraId {
  let era: EraId = parameters.turnStructure.eras[0]!.id;
  for (const candidate of parameters.turnStructure.eras) {
    if (turn >= candidate.fromTurn) {
      era = candidate.id;
    }
  }
  return era;
}

const ERA_ORDER: Record<EraId, number> = { early: 0, mid: 1, late: 2 };

// ---------------------------------------------------------------------------
// Action handlers (all operate on state.actingSeat)
// ---------------------------------------------------------------------------

function handleAllocate(
  data: EngineData,
  state: GameState,
  action: Extract<Action, { type: 'allocate' }>,
): void {
  const seat = state.actingSeat;
  const seatState = state.seats[seat];
  const { capability, safety, diffusion } = action;
  if (
    ![capability, safety, diffusion].every((v) => Number.isInteger(v) && v >= 0) ||
    capability + safety + diffusion !== ALLOCATION_TOTAL
  ) {
    throw new EngineError('badAllocation', 'allocation shares must be >=0 and sum to 100');
  }
  const paused = seatState.flags.includes('forcedPause');
  if (paused) {
    if (capability > FORCED_PAUSE_CAPABILITY_MAX) {
      throw new EngineError(
        'badAllocation',
        `forced pause: capability share is capped at ${FORCED_PAUSE_CAPABILITY_MAX} this turn`,
      );
    }
    seatState.flags = seatState.flags.filter((f) => f !== 'forcedPause');
  }
  seatState.allocation = { capability, safety, diffusion };

  const rndCurve = data.parameters.curves['rndCapacity'];
  const capCurve = data.parameters.curves['capabilityPerRnd'];
  if (!rndCurve || !capCurve) {
    throw new EngineError('badAllocation', 'parameters must define rndCapacity/capabilityPerRnd');
  }
  const rndPoints = evalCurve(rndCurve, seatState.resources.compute + seatState.resources.talent);
  const capPts = mulDiv(rndPoints, capability, 100);
  const safetyPts = mulDiv(rndPoints, safety, 100);
  const diffusionPts = mulDiv(rndPoints, diffusion, 100);

  let capabilityGain = evalCurve(capCurve, capPts);
  // The chokepoint with teeth: while the export crackdown holds, the gated
  // seat's capability growth scales with how far substitution has come
  // (SRC-CSIS-EXPORT, SRC-SIM-GAMING-INSIGHTS#7 "slows, not stops").
  if (
    seatRules(data, seat).computeGatedBySubstitution &&
    state.world.flags.includes('exportCrackdown')
  ) {
    capabilityGain = mulDiv(capabilityGain, Math.max(250, seatState.substitution), 1000);
  }
  const before = seatState.resources.capability;
  seatState.resources.capability = clamp(before + capabilityGain, SCALE_MIN, SCALE_MAX);
  const insightGain = divRound(safetyPts, 2);
  seatState.resources.safetyInsight = clamp(
    seatState.resources.safetyInsight + insightGain,
    SCALE_MIN,
    SCALE_MAX,
  );

  seatState.turnScratch.capabilityGained = seatState.resources.capability - before;
  seatState.turnScratch.diffusionPts = diffusionPts;

  pushLog(state, seat, {
    kind: 'allocation',
    stringKey: null,
    deltas: {
      capability: seatState.resources.capability - before,
      safetyInsight: insightGain,
    },
    meta: { rndPoints, capPts, safetyPts, diffusionPts, paused },
  });
  state.phase = 'policy';
}

function effectiveCost(
  data: EngineData,
  seat: PlayableSeatId,
  card: PolicyCardData,
): { politicalCapital: number; capital: number } {
  const modifier = seatRules(data, seat).costModifiers?.[card.id];
  return {
    politicalCapital: Math.max(
      0,
      (card.cost?.politicalCapital ?? 0) + (modifier?.politicalCapital ?? 0),
    ),
    capital: Math.max(0, (card.cost?.capital ?? 0) + (modifier?.capital ?? 0)),
  };
}

function policyGateFailure(
  data: EngineData,
  state: GameState,
  seat: PlayableSeatId,
  card: PolicyCardData,
): string | null {
  if (seatRules(data, seat).policyUnavailable?.includes(card.id)) {
    return 'seatUnavailable';
  }
  const gates = card.gates;
  if (!gates) {
    return null;
  }
  const seatState = state.seats[seat];
  if (
    gates.publicTrustMin !== undefined &&
    seatState.resources.publicTrust < gates.publicTrustMin
  ) {
    return 'publicTrustMin';
  }
  if (
    gates.politicalCapitalMin !== undefined &&
    seatState.resources.politicalCapital < gates.politicalCapitalMin
  ) {
    return 'politicalCapitalMin';
  }
  if (gates.capabilityMin !== undefined && seatState.resources.capability < gates.capabilityMin) {
    return 'capabilityMin';
  }
  if (gates.eraMin !== undefined) {
    const current = eraForTurn(data.parameters, state.turn);
    if (ERA_ORDER[current] < ERA_ORDER[gates.eraMin]) {
      return 'eraMin';
    }
  }
  const view = flagsView(state, seat);
  if (gates.flagsAll && !gates.flagsAll.every((f) => view.has(f))) {
    return 'flagsAll';
  }
  if (gates.flagsNone && gates.flagsNone.some((f) => view.has(f))) {
    return 'flagsNone';
  }
  return null;
}

/** UI helper: which hand cards are playable right now, with lock reasons. */
export function playablePolicies(
  data: EngineData,
  state: GameState,
  seat?: PlayableSeatId,
): Array<{ id: string; playable: boolean; reason: string | null }> {
  const forSeat = seat ?? state.actingSeat;
  return state.seats[forSeat].policy.hand.map((id) => {
    const card = data.policies.find((p) => p.id === id);
    if (!card) {
      return { id, playable: false, reason: 'unknown' };
    }
    const gate = policyGateFailure(data, state, forSeat, card);
    if (gate) {
      return { id, playable: false, reason: gate };
    }
    if (!canAfford(data, state, forSeat, card)) {
      return { id, playable: false, reason: 'cost' };
    }
    return { id, playable: true, reason: null };
  });
}

function canAfford(
  data: EngineData,
  state: GameState,
  seat: PlayableSeatId,
  card: PolicyCardData,
): boolean {
  const cost = effectiveCost(data, seat, card);
  const seatState = state.seats[seat];
  return (
    seatState.resources.politicalCapital >= cost.politicalCapital &&
    seatState.resources.capital >= cost.capital
  );
}

function handlePlayPolicy(
  data: EngineData,
  state: GameState,
  action: Extract<Action, { type: 'playPolicy' }>,
): void {
  const seat = state.actingSeat;
  const seatState = state.seats[seat];
  const card = data.policies.find((p) => p.id === action.policyId);
  if (!card) {
    throw new EngineError('unknownPolicy', `no policy '${action.policyId}' in the deck`);
  }
  if (!seatState.policy.hand.includes(card.id)) {
    throw new EngineError('policyNotInHand', `policy '${card.id}' is not in hand`);
  }
  const gate = policyGateFailure(data, state, seat, card);
  if (gate) {
    throw new EngineError('policyGated', `policy '${card.id}' gated by ${gate}`);
  }
  if (!canAfford(data, state, seat, card)) {
    throw new EngineError('policyUnaffordable', `cannot afford policy '${card.id}'`);
  }

  const cost = effectiveCost(data, seat, card);
  seatState.resources.politicalCapital -= cost.politicalCapital;
  seatState.resources.capital -= cost.capital;
  applyEffects(state, seat, card.effects ?? {}, 'policyPlayed', {
    policyId: card.id,
    costPoliticalCapital: cost.politicalCapital,
    costCapital: cost.capital,
  });
  queueDelayed(state, seat, card.delayedEffects, 'policy', card.id, null);

  // Chosen gamble (the structural coup): outcome is stochastic BY the card's
  // own copy. Spiral odds read the shared relationship through the old
  // posture thresholds (treaty-grade trust calms it, rock bottom inflames it).
  if (card.gamble) {
    const gamble = card.gamble;
    let spiralProb = gamble.baseSpiralPerMille;
    const posture = postureFromTrust(data.parameters, state.world.bilateralTrust);
    spiralProb += gamble.postureModifiers?.[posture] ?? 0;
    const view = flagsView(state, seat);
    for (const mod of gamble.flagModifiers ?? []) {
      if (view.has(mod.flag)) {
        spiralProb += mod.deltaPerMille;
      }
    }
    spiralProb = clamp(spiralProb, 0, 1000);
    const [roll, nextWild] = nextInt(state.rng.wildcards, 1000);
    state.rng = { ...state.rng, wildcards: [...nextWild] as [number, number, number, number] };
    const spiraled = roll < spiralProb;
    applyEffects(state, seat, spiraled ? gamble.spiral : gamble.deter, 'policyPlayed', {
      policyId: card.id,
      gambleOutcome: spiraled ? 'spiral' : 'deter',
    });
    if (spiraled && gamble.spiralSetsPosture === 'race') {
      // A spiral craters the relationship to race-grade trust outright.
      const target = data.parameters.worldRules.postureChecks.raceTrustMax.value;
      if (state.world.bilateralTrust > target) {
        const drop = target - state.world.bilateralTrust;
        applyDelta(state, seat, 'rival.trust', drop);
        pushLog(state, null, {
          kind: 'rivalPostureChange',
          stringKey: null,
          deltas: { 'rival.trust': drop },
          meta: { cause: card.id, to: 'race' },
        });
      }
    }
  }

  seatState.policy.hand = seatState.policy.hand.filter((id) => id !== card.id);
  seatState.policy.playedThisTurn = card.id;
  if (card.oncePerRun) {
    seatState.policy.spent = [...seatState.policy.spent, card.id].sort();
  } else if (card.cooldown) {
    seatState.policy.cooldowns[card.id] = state.turn + card.cooldown;
  }
  if (card.tags.includes('diplomacy') || card.tags.includes('treaty')) {
    seatState.turnScratch.playedDiplomacy = true;
  }

  drawEvent(data, state);
}

function handleSkipPolicy(data: EngineData, state: GameState): void {
  state.seats[state.actingSeat].policy.playedThisTurn = null;
  drawEvent(data, state);
}

// ---------------------------------------------------------------------------
// Events (per-seat draws from shared pools; symmetric uncertainty)
// ---------------------------------------------------------------------------

function eventStream(seat: PlayableSeatId): RngStreamName {
  return seat === 'usa' ? 'eventsUsa' : 'eventsChina';
}

function eventEligible(
  data: EngineData,
  state: GameState,
  seat: PlayableSeatId,
  card: ChoiceEventData,
): boolean {
  const seatState = state.seats[seat];
  if (!card.repeatable && seatState.firedEvents.includes(card.id)) {
    return false;
  }
  const trigger = card.trigger;
  if (trigger.era !== undefined && trigger.era !== eraForTurn(data.parameters, state.turn)) {
    return false;
  }
  if (trigger.turnMin !== undefined && state.turn < trigger.turnMin) {
    return false;
  }
  if (trigger.turnMax !== undefined && state.turn > trigger.turnMax) {
    return false;
  }
  const conditions = trigger.conditions;
  if (conditions) {
    if (
      conditions.rivalPosture !== undefined &&
      postureFromTrust(data.parameters, state.world.bilateralTrust) !== conditions.rivalPosture
    ) {
      return false;
    }
    const view = flagsView(state, seat);
    if (conditions.flagsAll && !conditions.flagsAll.every((f) => view.has(f))) {
      return false;
    }
    if (conditions.flagsNone && conditions.flagsNone.some((f) => view.has(f))) {
      return false;
    }
    for (const [key, min] of Object.entries(conditions.resourceMin ?? {})) {
      if (seatState.resources[key as keyof SeatState['resources']] < (min as number)) {
        return false;
      }
    }
    for (const [key, max] of Object.entries(conditions.resourceMax ?? {})) {
      if (seatState.resources[key as keyof SeatState['resources']] > (max as number)) {
        return false;
      }
    }
    for (const [key, min] of Object.entries(conditions.societyMin ?? {})) {
      if (seatState.society[key as keyof SeatState['society']] < (min as number)) {
        return false;
      }
    }
    for (const [key, max] of Object.entries(conditions.societyMax ?? {})) {
      if (seatState.society[key as keyof SeatState['society']] > (max as number)) {
        return false;
      }
    }
  }
  return true;
}

/**
 * FIXED beats take the memo slot when due, PER SEAT: calendar beats (EU AI
 * Act) reach both desks; milestone beats fire when THAT seat crosses the
 * line. Historical and closing-window beats outrank conditional ones.
 */
function fixedBeatDue(
  data: EngineData,
  state: GameState,
  seat: PlayableSeatId,
): FixedEventData | null {
  const seatState = state.seats[seat];
  const beats = data.events
    .filter((card): card is FixedEventData => card.kind === 'fixed')
    .filter((card) => !seatState.firedEvents.includes(card.id))
    .sort((a, b) => {
      if (a.historical !== b.historical) {
        return a.historical ? -1 : 1;
      }
      if (a.fixedTurn.max !== b.fixedTurn.max) {
        return a.fixedTurn.max - b.fixedTurn.max;
      }
      return a.id < b.id ? -1 : 1;
    });
  for (const card of beats) {
    if (state.turn < card.fixedTurn.min || state.turn > card.fixedTurn.max) {
      continue;
    }
    if (!card.historical) {
      const cond = card.condition!;
      if (cond.era !== undefined && cond.era !== eraForTurn(data.parameters, state.turn)) {
        continue;
      }
      if (cond.minCapability !== undefined && seatState.resources.capability < cond.minCapability) {
        continue;
      }
      const view = flagsView(state, seat);
      if (cond.flagsAll && !cond.flagsAll.every((f) => view.has(f))) {
        continue;
      }
      if (cond.flagsNone && cond.flagsNone.some((f) => view.has(f))) {
        continue;
      }
      if (cond.diceScaledFireProb !== undefined) {
        const stream = eventStream(seat);
        const [roll, nextRng] = nextInt(state.rng[stream], 1000);
        state.rng = { ...state.rng, [stream]: [...nextRng] as [number, number, number, number] };
        if (roll >= state.world.takeoffSteepness) {
          continue;
        }
      }
    }
    return card;
  }
  return null;
}

/** After a seat's event resolves (or no memo exists): China's window or the world update. */
function afterSeatWindow(data: EngineData, state: GameState): void {
  if (state.actingSeat === 'usa') {
    state.actingSeat = 'china';
    state.phase = 'allocate';
    return;
  }
  worldUpdate(data, state);
}

function drawEvent(data: EngineData, state: GameState): void {
  const seat = state.actingSeat;
  const seatState = state.seats[seat];
  const beat = fixedBeatDue(data, state, seat);
  if (beat) {
    seatState.pendingEvents = [{ eventId: beat.id, drawnOnTurn: state.turn }];
    pushLog(state, seat, {
      kind: 'eventDrawn',
      stringKey: beat.title,
      deltas: null,
      meta: { eventId: beat.id, kind: 'fixed', historical: beat.historical },
    });
    state.phase = 'event';
    return;
  }
  // One memo desk per quarter, alternating: the USA's memo lands on odd
  // turns, China's on even ones. Two full seats drawing every turn would
  // double the solo game's card inflow and collapse the pacing; alternation
  // keeps it and gives each seat the quiet/crisis rhythm (design-note E).
  const memoTurn = seat === 'usa' ? state.turn % 2 === 1 : state.turn % 2 === 0;
  if (!memoTurn) {
    afterSeatWindow(data, state);
    return;
  }
  const pool = data.events
    .filter((card): card is ChoiceEventData => card.kind === 'choice')
    .filter((card) => eventEligible(data, state, seat, card))
    .sort((a, b) => (a.id < b.id ? -1 : 1));
  if (pool.length === 0) {
    afterSeatWindow(data, state);
    return;
  }
  const stream = eventStream(seat);
  const [index, nextRng] = weightedIndex(
    state.rng[stream],
    pool.map((card) => card.trigger.weight),
  );
  state.rng = { ...state.rng, [stream]: [...nextRng] as [number, number, number, number] };
  const drawn = pool[index]!;
  seatState.pendingEvents = [{ eventId: drawn.id, drawnOnTurn: state.turn }];
  pushLog(state, seat, {
    kind: 'eventDrawn',
    stringKey: drawn.title,
    deltas: null,
    meta: { eventId: drawn.id, kind: 'choice' },
  });
  state.phase = 'event';
}

function handleResolveEvent(
  data: EngineData,
  state: GameState,
  action: Extract<Action, { type: 'resolveEventChoice' }>,
): void {
  const seat = state.actingSeat;
  const seatState = state.seats[seat];
  const pending = seatState.pendingEvents[0];
  if (!pending || pending.eventId !== action.eventId) {
    throw new EngineError('wrongEvent', `event '${action.eventId}' is not pending`);
  }
  const card = data.events.find((e) => e.id === pending.eventId)!;
  if (card.kind === 'wildcard') {
    throw new EngineError('wrongEvent', `wildcard '${card.id}' cannot be resolved as a memo`);
  }
  const choice = card.choices[action.choiceIndex];
  if (!choice) {
    throw new EngineError('badChoice', `event '${card.id}' has no choice ${action.choiceIndex}`);
  }
  applyEffects(state, seat, choice.effects ?? {}, 'eventResolved', {
    eventId: card.id,
    choiceIndex: action.choiceIndex,
  });
  queueDelayed(state, seat, choice.delayedEffects, 'event', card.id, action.choiceIndex);
  seatState.firedEvents = [...seatState.firedEvents, card.id].sort();
  seatState.pendingEvents = [];
  afterSeatWindow(data, state);
}

// ---------------------------------------------------------------------------
// Incidents (per seat) and wildcards (world-level)
// ---------------------------------------------------------------------------

function incidentStream(seat: PlayableSeatId): RngStreamName {
  return seat === 'usa' ? 'incidentsUsa' : 'incidentsChina';
}

/** Incident check for one seat. Returns true if a rung-3 catastrophe ended the run. */
function runIncidentCheck(data: EngineData, state: GameState, seat: PlayableSeatId): boolean {
  const seatState = state.seats[seat];
  const incidents = data.incidents;
  const baseRisk = mulDiv(
    seatState.resources.capability,
    SCALE_MAX - seatState.hidden.trueAlignment,
    SCALE_MAX,
  );
  let pressurePct = 100;
  if (seatState.allocation.capability >= data.parameters.alignmentModel.crashThresholdShare.value) {
    pressurePct += incidents.riskFormula.pressureAllocationPct.value;
  }
  // An open race is pressure for BOTH sides: rock-bottom bilateral trust.
  if (postureFromTrust(data.parameters, state.world.bilateralTrust) === 'race') {
    pressurePct += incidents.riskFormula.pressureRivalRacePct.value;
  }
  const risk = clamp(mulDiv(baseRisk, pressurePct, 100), 0, SCALE_MAX);

  let rung: (typeof incidents.rungs)[number] | null = null;
  for (const candidate of incidents.rungs) {
    const cooldownUntil = seatState.incidentCooldowns[candidate.id] ?? 0;
    if (risk > candidate.threshold && state.turn >= cooldownUntil) {
      rung = candidate;
    }
  }
  if (!rung) {
    return false;
  }
  const fireProb = Math.min(500, risk - rung.threshold);
  const stream = incidentStream(seat);
  const [roll, nextIncidents] = nextInt(state.rng[stream], 1000);
  state.rng = { ...state.rng, [stream]: [...nextIncidents] as [number, number, number, number] };
  if (roll >= fireProb) {
    return false;
  }

  const maxReduction = incidents.safetyInsightDamageReductionMaxPerMille.value;
  const reduction = Math.min(
    maxReduction,
    mulDiv(seatState.resources.safetyInsight, maxReduction, SCALE_MAX),
  );
  const deltas: Partial<Record<EffectTarget, number>> = {};
  for (const [key, value] of Object.entries(rung.baseDamage)) {
    if (key === 'flags') {
      for (const flag of value as string[]) {
        setFlagFor(state, seat, flag);
      }
      continue;
    }
    if (typeof value === 'number') {
      const reduced = mulDiv(value, 1000 - reduction, 1000);
      const applied = applyDelta(state, seat, key as EffectTarget, reduced);
      if (applied !== 0) {
        deltas[key as EffectTarget] = applied;
      }
    }
  }
  seatState.incidentCooldowns = {
    ...seatState.incidentCooldowns,
    [rung.id]: state.turn + rung.cooldownTurns,
  };
  if (rung.forcedPause) {
    setFlagFor(state, seat, 'forcedPause');
  }
  pushLog(state, seat, {
    kind: 'incident',
    stringKey: rung.title,
    deltas,
    meta: {
      rungId: rung.id,
      ladder: rung.ladder,
      risk,
      reductionPerMille: reduction,
      forcedPause: rung.forcedPause,
    },
  });
  if (
    rung.catastropheBelowTrueAlignment !== undefined &&
    seatState.hidden.trueAlignment < rung.catastropheBelowTrueAlignment
  ) {
    endRun(state, 'misalignedCatastrophe', {
      trigger: 'labAccident',
      causeSeat: seat,
      trueAlignment: seatState.hidden.trueAlignment,
      alignmentDifficulty: state.world.alignmentDifficulty,
    });
    return true;
  }
  return false;
}

function wildcardEligibleFor(
  state: GameState,
  card: WildcardEventData,
  seat: PlayableSeatId,
): boolean {
  const eligible = card.fire.eligible;
  if (!eligible) {
    return true;
  }
  const seatState = state.seats[seat];
  if (eligible.turnMin !== undefined && state.turn < eligible.turnMin) {
    return false;
  }
  if (
    eligible.minCapability !== undefined &&
    seatState.resources.capability < eligible.minCapability
  ) {
    return false;
  }
  if (
    eligible.computeOverEnergyMin !== undefined &&
    seatState.resources.compute - seatState.resources.energy < eligible.computeOverEnergyMin
  ) {
    return false;
  }
  const view = flagsView(state, seat);
  if (eligible.flagsAll && !eligible.flagsAll.every((f) => view.has(f))) {
    return false;
  }
  if (eligible.flagsNone && eligible.flagsNone.some((f) => view.has(f))) {
    return false;
  }
  return true;
}

function exposureValue(
  seatState: SeatState,
  exposure: 'capability' | 'compute' | 'computeMinusEnergy',
): number {
  if (exposure === 'capability') {
    return seatState.resources.capability;
  }
  if (exposure === 'compute') {
    return seatState.resources.compute;
  }
  return clamp(seatState.resources.compute - seatState.resources.energy, 0, SCALE_MAX);
}

/** Apply one wildcard to one seat (seat-relative effects, exposure-scaled). */
function applyWildcardTo(state: GameState, card: WildcardEventData, seat: PlayableSeatId): void {
  const seatState = state.seats[seat];
  const view = flagsView(state, seat);
  const deltas: Partial<Record<EffectTarget, number>> = {};
  for (const [key, value] of Object.entries(card.effects ?? {})) {
    if (key === 'flags') {
      for (const flag of value as string[]) {
        setFlagFor(state, seat, flag);
      }
      continue;
    }
    if (key === 'clearFlags') {
      for (const flag of value as string[]) {
        clearFlagFor(state, seat, flag);
      }
      continue;
    }
    if (typeof value === 'number') {
      const applied = applyDelta(state, seat, key as EffectTarget, value);
      if (applied !== 0) {
        deltas[key as EffectTarget] = applied;
      }
    }
  }
  for (const scaled of card.scaledEffects ?? []) {
    let delta = scaled.base + mulDiv(scaled.coef, exposureValue(seatState, scaled.exposure), 1000);
    if (scaled.halveIfFlag && view.has(scaled.halveIfFlag)) {
      delta = divRound(delta, 2);
    }
    const applied = applyDelta(state, seat, scaled.target, delta);
    if (applied !== 0) {
      deltas[scaled.target] = (deltas[scaled.target] ?? 0) + applied;
    }
  }
  queueDelayed(state, seat, card.delayedEffects, 'event', card.id, null);
  pushLog(state, seat, {
    kind: 'wildcard',
    stringKey: card.title,
    deltas,
    meta: { eventId: card.id },
  });
}

/**
 * One wildcard check per turn, world-level. Systemic shocks (chips, grid,
 * regulation) hit every eligible seat through its OWN exposure. Theft-type
 * wildcards (any scaled effect targeting rival.*) hit ONE victim: the seat
 * with the most to steal (highest exposure; USA on ties, documented).
 */
function runWildcardCheck(data: EngineData, state: GameState): void {
  if (state.turn < state.world.wildcardGlobalUntil) {
    return;
  }
  const pool = data.events
    .filter((card): card is WildcardEventData => card.kind === 'wildcard')
    .sort((a, b) => (a.id < b.id ? -1 : 1));
  for (const card of pool) {
    if (state.turn < (state.world.wildcardCooldowns[card.id] ?? 0)) {
      continue;
    }
    const eligibleSeats = PLAYABLE_SEAT_IDS.filter((seat) =>
      wildcardEligibleFor(state, card, seat),
    );
    if (eligibleSeats.length === 0) {
      continue;
    }
    // Theft-type wildcards (any rival.* scaled effect) hit ONE victim: the
    // seat with the most to steal. Its flags, not the world's, set the odds.
    const theftType = (card.scaledEffects ?? []).some((s) => s.target.startsWith('rival.'));
    const victim = theftType
      ? eligibleSeats.reduce((best, seat) =>
          exposureValue(state.seats[seat], card.scaledEffects![0]!.exposure) >
          exposureValue(state.seats[best], card.scaledEffects![0]!.exposure)
            ? seat
            : best,
        )
      : null;
    let prob = card.fire.probPerMille;
    for (const mod of card.fire.probModifiers ?? []) {
      const applies = victim
        ? flagsView(state, victim).has(mod.flag)
        : eligibleSeats.some((seat) => flagsView(state, seat).has(mod.flag));
      if (applies) {
        prob += mod.deltaPerMille;
      }
    }
    prob = clamp(prob, 0, 1000);
    if (prob === 0) {
      continue;
    }
    const [roll, nextWild] = nextInt(state.rng.wildcards, 1000);
    state.rng = { ...state.rng, wildcards: [...nextWild] as [number, number, number, number] };
    if (roll >= prob) {
      continue;
    }

    if (victim) {
      applyWildcardTo(state, card, victim);
    } else {
      for (const seat of eligibleSeats) {
        applyWildcardTo(state, card, seat);
      }
    }
    state.world.wildcardCooldowns = {
      ...state.world.wildcardCooldowns,
      [card.id]: state.turn + card.fire.cooldownTurns,
    };
    state.world.wildcardGlobalUntil = state.turn + 2;
    return;
  }
}

// ---------------------------------------------------------------------------
// World update (once per turn, after both seats acted)
// ---------------------------------------------------------------------------

/** Milestone self-acceleration: highest crossed rung, scaled by the shared die. */
function ladderAccel(
  data: EngineData,
  state: GameState,
  capability: number,
): { milestoneId: string; bonus: number } | null {
  let crossed: { id: string; selfAccel: number } | null = null;
  for (const milestone of data.parameters.capabilityLadder.milestones) {
    if (capability >= milestone.at.value) {
      crossed = { id: milestone.id, selfAccel: milestone.selfAccel.value };
    }
  }
  if (!crossed) {
    return null;
  }
  const bonus = mulDiv(crossed.selfAccel, state.world.takeoffSteepness, 1000);
  return bonus > 0 ? { milestoneId: crossed.id, bonus } : null;
}

function seatWorldPass(data: EngineData, state: GameState, seat: PlayableSeatId): boolean {
  const seatState = state.seats[seat];
  const rules = data.parameters.worldRules;

  // 0. Takeoff self-acceleration: milestones feed themselves.
  const accel = ladderAccel(data, state, seatState.resources.capability);
  if (accel) {
    const before = seatState.resources.capability;
    seatState.resources.capability = clamp(before + accel.bonus, 0, SCALE_MAX);
    const applied = seatState.resources.capability - before;
    if (applied !== 0) {
      pushLog(state, seat, {
        kind: 'upkeep',
        stringKey: null,
        deltas: { capability: applied },
        meta: { rule: 'selfAcceleration', milestone: accel.milestoneId },
      });
    }
  }

  // 1. Society: displacement drifts toward the shared exposure curve at the
  // preset's lag; diffusion converts to relief and trust; unrest drags.
  const society = rules.society;
  const displacementCurve = data.parameters.curves['displacementFromCapability'];
  let displacementGain = 0;
  if (displacementCurve) {
    const lagDivisor =
      data.parameters.worldviewPresets[state.presetId].displacementLagDivisor.value;
    const target = evalCurve(displacementCurve, seatState.resources.capability);
    displacementGain = divRound(
      target - seatState.society.jobDisplacement,
      Math.max(1, lagDivisor),
    );
  }
  const reliefUnits = Math.floor(
    seatState.turnScratch.diffusionPts / Math.max(1, society.diffusionReliefPer.value),
  );
  const reliefApplied = Math.min(
    reliefUnits * 50,
    Math.max(0, seatState.society.jobDisplacement + displacementGain),
  );
  const trustFromDiffusion = Math.max(0, reliefUnits * 50 - reliefApplied) > 0 ? 50 : 0;
  seatState.society.jobDisplacement = clamp(
    seatState.society.jobDisplacement + displacementGain - reliefApplied,
    0,
    SCALE_MAX,
  );
  let unrestGain = 0;
  if (seatState.society.jobDisplacement > seatState.resources.publicTrust) {
    unrestGain += society.unrestFromDisplacementGap.value;
  }
  if (seatState.society.jobDisplacement >= society.unrestSurgeDisplacement.value) {
    unrestGain += society.unrestFromDisplacementGap.value;
  }
  seatState.society.unrest = clamp(seatState.society.unrest + unrestGain, 0, SCALE_MAX);
  let trustDelta = trustFromDiffusion;
  const trustCurve = data.parameters.curves['trustFromUnrest'];
  if (trustCurve) {
    trustDelta += divRound(
      evalCurve(trustCurve, seatState.society.unrest),
      Math.max(1, rules.societyDepth.trustCurveDivisor.value),
    );
  }
  seatState.resources.publicTrust = clamp(
    seatState.resources.publicTrust + trustDelta,
    0,
    SCALE_MAX,
  );
  let economicDrag = 0;
  if (seatState.society.unrest >= rules.societyDepth.unrestEconomicDragMin.value) {
    economicDrag = rules.societyDepth.unrestEconomicDrag.value;
    seatState.resources.capital = clamp(seatState.resources.capital - economicDrag, 0, SCALE_MAX);
    seatState.resources.talent = clamp(
      seatState.resources.talent - divRound(economicDrag, 2),
      0,
      SCALE_MAX,
    );
  }
  const societyDeltas: Partial<Record<EffectTarget, number>> = {};
  if (displacementGain - reliefApplied !== 0) {
    societyDeltas['society.jobDisplacement'] = displacementGain - reliefApplied;
  }
  if (unrestGain !== 0) {
    societyDeltas['society.unrest'] = unrestGain;
  }
  if (trustDelta !== 0) {
    societyDeltas.publicTrust = trustDelta;
  }
  if (economicDrag !== 0) {
    societyDeltas.capital = -economicDrag;
  }
  pushLog(state, seat, {
    kind: 'societyUpdate',
    stringKey: null,
    deltas: societyDeltas,
    meta: { reliefApplied },
  });

  // 2. True alignment drift: safety work earns it; racing-heavy corner-cuts it.
  const safetyPts = mulDiv(
    evalCurve(
      data.parameters.curves['rndCapacity']!,
      seatState.resources.compute + seatState.resources.talent,
    ),
    seatState.allocation.safety,
    100,
  );
  // Safety work EARNS alignment, slowly. Two forces cut against it: racing-
  // heavy allocation corners it, and the frontier itself erodes it once
  // capability enters the fog zone. Alignment must be banked before the final
  // sprint, and even then verification is a gamble (that is the whole game).
  const alignModel = data.parameters.alignmentModel;
  let alignmentDrift = divRound(safetyPts, alignModel.safetyDriftDivisor.value);
  if (seatState.resources.capability >= data.parameters.thresholds.fogZoneStart.value) {
    alignmentDrift -= alignModel.fogZoneAlignmentErosion.value;
  }
  if (seatState.allocation.capability >= alignModel.crashThresholdShare.value) {
    alignmentDrift -= alignModel.crashPenalty.value;
  }
  seatState.hidden.trueAlignment = clamp(
    seatState.hidden.trueAlignment + alignmentDrift,
    0,
    SCALE_MAX,
  );

  // 3. Agency erosion (Gradual Disempowerment hook; silent, per seat).
  const erosion = rules.agencyErosion;
  if (seatState.resources.capability >= erosion.highCapabilityMin.value) {
    const shielded = seatState.allocation.diffusion >= erosion.diffusionShieldMin.value;
    const accrual = shielded ? divRound(erosion.perTurn.value, 2) : erosion.perTurn.value;
    seatState.hidden.agencyErosion = clamp(seatState.hidden.agencyErosion + accrual, 0, SCALE_MAX);
  }

  // 4. Incidents: the hidden dice LEAKING, per seat.
  if (runIncidentCheck(data, state, seat)) {
    return true;
  }

  // 5. Institutional rhythm: the midterm (USA, turn 8) or the era legitimacy
  // verdict (China, each era turn after the first).
  const rulesForSeat = seatRules(data, seat);
  if (rulesForSeat.elections && state.turn === data.parameters.turnStructure.electionTurn.value) {
    const election = rules.election;
    const renewed =
      seatState.resources.publicTrust >= election.trustMin.value &&
      seatState.society.unrest <= election.unrestMax.value;
    const swing = renewed ? election.mandateSwing.value : -election.mandateSwing.value;
    seatState.resources.politicalCapital = clamp(
      seatState.resources.politicalCapital + swing,
      0,
      SCALE_MAX,
    );
    pushLog(state, seat, {
      kind: 'election',
      stringKey: null,
      deltas: { politicalCapital: swing },
      meta: { renewed },
    });
  }
  const legitimacy = rulesForSeat.legitimacyCheck;
  if (
    legitimacy &&
    data.parameters.turnStructure.eras.some((era, i) => i > 0 && era.fromTurn === state.turn)
  ) {
    const holds = seatState.resources.publicTrust >= legitimacy.trustMin.value;
    const swing = holds ? legitimacy.swing.value : -legitimacy.swing.value;
    seatState.resources.politicalCapital = clamp(
      seatState.resources.politicalCapital + swing,
      0,
      SCALE_MAX,
    );
    pushLog(state, seat, {
      kind: 'election',
      stringKey: null,
      deltas: { politicalCapital: swing },
      meta: { renewed: holds, legitimacy: true },
    });
  }

  // 6. Eval report: the band around a truth this seat never sees.
  const evalParams = data.parameters.evalUncertainty;
  const band = Math.max(
    evalParams.floorBandWidth.value,
    evalParams.baseBandWidth.value -
      mulDiv(evalParams.safetyInsightNarrowing.value, seatState.resources.safetyInsight, 100),
  );
  let deceptionLift = 0;
  if (seatState.hidden.trueAlignment < 500) {
    const rawLift = mulDiv(
      500 - seatState.hidden.trueAlignment,
      evalParams.deceptionMaxLift.value,
      500,
    );
    const counter = mulDiv(
      evalParams.deceptionInsightCounter.value,
      seatState.resources.safetyInsight,
      100,
    );
    deceptionLift = Math.max(0, rawLift - counter);
  }
  const quarter = Math.max(1, divRound(band, 4));
  const [jitter, nextHidden] = nextIntInRange(state.rng.hiddenDice, -quarter, quarter);
  state.rng = { ...state.rng, hiddenDice: [...nextHidden] as [number, number, number, number] };
  const center = clamp(seatState.hidden.trueAlignment + deceptionLift + jitter, 0, SCALE_MAX);
  const report = {
    turn: state.turn,
    bandLow: clamp(center - divRound(band, 2), 0, SCALE_MAX),
    bandHigh: clamp(center + divRound(band, 2), 0, SCALE_MAX),
  };
  seatState.evalHistory = [...seatState.evalHistory, report];
  pushLog(state, seat, {
    kind: 'evalReport',
    stringKey: null,
    deltas: null,
    meta: { bandLow: report.bandLow, bandHigh: report.bandHigh },
  });
  return false;
}

function worldUpdate(data: EngineData, state: GameState): void {
  const thresholds = data.parameters.thresholds;

  for (const seat of PLAYABLE_SEAT_IDS) {
    if (seatWorldPass(data, state, seat)) {
      return; // a rung-3 catastrophe ended the run
    }
  }

  // The relationship has its own temperature: an open race bleeds trust, a
  // treaty-grade one builds it, and diplomacy warms the middle (the v0.1
  // posture trust dynamics, unchanged parameters, now symmetric).
  const posture = postureFromTrust(data.parameters, state.world.bilateralTrust);
  const rivalMoves = data.parameters.worldRules.rivalMoves;
  let trustDrift = 0;
  if (posture === 'race') {
    trustDrift = rivalMoves.race.trust.value;
  } else if (posture === 'cautious') {
    trustDrift = rivalMoves.cautious.trust.value;
  } else if (PLAYABLE_SEAT_IDS.some((seat) => state.seats[seat].turnScratch.playedDiplomacy)) {
    trustDrift = rivalMoves.mirror.diplomacyTrust.value;
  }
  if (trustDrift !== 0) {
    const before = state.world.bilateralTrust;
    state.world.bilateralTrust = clamp(before + trustDrift, 0, SCALE_MAX);
    const applied = state.world.bilateralTrust - before;
    if (applied !== 0) {
      pushLog(state, null, {
        kind: 'rivalAction',
        stringKey: null,
        deltas: { 'rival.trust': applied },
        meta: { posture },
      });
    }
  }

  // World-level shocks after both seats' passes.
  runWildcardCheck(data, state);

  // Ending checks. Breakdown first: a society that stops decides the race by
  // no longer caring who wins it, whichever side of the Pacific it is on.
  for (const seat of PLAYABLE_SEAT_IDS) {
    if (state.seats[seat].society.unrest >= thresholds.breakdownUnrest.value) {
      endRun(state, 'societalBreakdown', { trigger: 'unrest', seat });
      return;
    }
  }

  // Threshold crossings: the seat furthest along resolves first (USA on ties,
  // documented). The crosser's OWN alignment faces the SHARED difficulty; a
  // failed gamble is a catastrophe for everyone (takeaway 1 with teeth).
  const crossingOrder = [...PLAYABLE_SEAT_IDS].sort(
    (a, b) => state.seats[b].resources.capability - state.seats[a].resources.capability,
  );
  for (const seat of crossingOrder) {
    if (state.seats[seat].resources.capability >= thresholds.capabilityThreshold.value) {
      resolveCrossing(state, seat, { trigger: 'threshold' });
      return;
    }
  }

  // Treaty: a BILATERAL act. The channel is open, trust is treaty-grade, it is
  // late enough that both sides survived the dangerous middle, BOTH seats have
  // signaled at least once (each played the feeler), and one co-signs this turn.
  // A treaty you sign alone is not a treaty (takeaway 4: cooperation is hard).
  if (
    state.world.flags.includes('treatyChannel') &&
    state.world.bilateralTrust >= thresholds.treatyTrustMin.value &&
    state.turn >= thresholds.treatySignTurnMin.value &&
    PLAYABLE_SEAT_IDS.every((seat) => state.seats[seat].flags.includes('treatySignaled')) &&
    PLAYABLE_SEAT_IDS.some(
      (seat) => state.seats[seat].policy.playedThisTurn === 'compute_treaty_feeler',
    )
  ) {
    endRun(state, 'negotiatedSlowdown', { trigger: 'treatySigned' });
    return;
  }

  state.phase = 'report';
}

function resolveCrossing(
  state: GameState,
  seat: PlayableSeatId,
  meta: Record<string, string | number | boolean>,
): void {
  const seatState = state.seats[seat];
  const passed = seatState.hidden.trueAlignment >= state.world.alignmentDifficulty;
  if (!passed) {
    endRun(state, 'misalignedCatastrophe', {
      ...meta,
      causeSeat: seat,
      trueAlignment: seatState.hidden.trueAlignment,
      alignmentDifficulty: state.world.alignmentDifficulty,
    });
    return;
  }
  endRun(state, seat === state.playerSeat ? 'flourishing' : 'outpaced', {
    ...meta,
    winnerSeat: seat,
    trueAlignment: seatState.hidden.trueAlignment,
    alignmentDifficulty: state.world.alignmentDifficulty,
  });
}

function endRun(
  state: GameState,
  endingId: GameState['endingId'] & string,
  meta: Record<string, string | number | boolean>,
): void {
  state.endingId = endingId;
  state.phase = 'ended';
  pushLog(state, null, {
    kind: 'ending',
    stringKey: null,
    deltas: null,
    meta: { endingId, ...meta },
  });
}

// ---------------------------------------------------------------------------
// Advance + upkeep
// ---------------------------------------------------------------------------

function handleAdvance(data: EngineData, state: GameState): void {
  const maxTurns = data.parameters.turnStructure.maxTurns.value;
  if (state.turn >= maxTurns) {
    finalResolution(data, state);
    return;
  }
  state.turn += 1;
  for (const seat of PLAYABLE_SEAT_IDS) {
    upkeep(data, state, seat);
  }
  // Ticker draw (flavor selection for the UI; separate stream by design).
  const [, nextRng] = drawFromStream(state.rng, 'ticker', 1000);
  state.rng = nextRng;
  state.actingSeat = 'usa';
  state.phase = 'allocate';
}

/** Turn-limit resolution incl. the unresolved-2030 rule (windowStillOpen). */
function finalResolution(data: EngineData, state: GameState): void {
  const thresholds = data.parameters.thresholds;
  const crossingOrder = [...PLAYABLE_SEAT_IDS].sort(
    (a, b) => state.seats[b].resources.capability - state.seats[a].resources.capability,
  );
  for (const seat of crossingOrder) {
    if (state.seats[seat].resources.capability >= thresholds.fogZoneStart.value) {
      resolveCrossing(state, seat, { trigger: 'turnLimitInFog' });
      return;
    }
  }
  setFlagFor(state, state.playerSeat, 'windowStillOpen');
  // Nearest tendency from the PLAYER seat's perspective; ties in order.
  const player = state.seats[state.playerSeat];
  const rival = state.seats[otherSeat(state.playerSeat)];
  const scores: Array<[GameState['endingId'] & string, number]> = [
    ['outpaced', rival.resources.capability - player.resources.capability],
    ['societalBreakdown', player.society.unrest - divRound(thresholds.breakdownUnrest.value, 2)],
    [
      'negotiatedSlowdown',
      state.world.flags.includes('treatyChannel') ? state.world.bilateralTrust - 500 : -1000,
    ],
    [
      'flourishing',
      divRound(
        player.resources.publicTrust +
          (1000 - player.society.unrest) +
          player.resources.safetyInsight,
        3,
      ) - 500,
    ],
  ];
  let best = scores[0]!;
  for (const candidate of scores) {
    if (candidate[1] > best[1]) {
      best = candidate;
    }
  }
  endRun(state, best[0], { trigger: 'turnLimit', windowStillOpen: true, score: best[1] });
}

function upkeep(data: EngineData, state: GameState, seat: PlayableSeatId): void {
  const seatState = state.seats[seat];
  // Capital income from last turn's diffusion (before scratch reset).
  const income = mulDiv(
    seatState.turnScratch.diffusionPts,
    data.parameters.worldRules.upkeep.capitalIncomePerDiffusion.value,
    100,
  );
  if (income !== 0) {
    seatState.resources.capital = clamp(seatState.resources.capital + income, 0, SCALE_MAX);
  }
  const skippedLastTurn = seatState.policy.playedThisTurn === null;
  seatState.turnScratch = { capabilityGained: 0, diffusionPts: 0, playedDiplomacy: false };
  seatState.policy.playedThisTurn = null;

  pushLog(state, seat, {
    kind: 'turnStart',
    stringKey: null,
    deltas: income !== 0 ? { capital: income } : null,
    meta: { era: eraForTurn(data.parameters, state.turn) },
  });

  // Delayed effects due this turn.
  const due = seatState.delayed.filter((d) => d.dueTurn === state.turn);
  seatState.delayed = seatState.delayed.filter((d) => d.dueTurn !== state.turn);
  for (const delayed of due) {
    applyEffects(state, seat, delayed.effects, 'delayedEffect', {
      sourceKind: delayed.sourceKind,
      sourceId: delayed.sourceId,
    });
  }

  // Mandates: assign at each era's first turn, then resolve active ones.
  const eraStarting = data.parameters.turnStructure.eras.find((e) => e.fromTurn === state.turn);
  if (eraStarting) {
    assignEraMandates(data, state, seat, eraStarting.id);
  }
  checkMandates(data, state, seat);

  // Grid limit: compute cannot outrun energy forever.
  const slack = data.parameters.thresholds.gridSlackBeforeCap.value;
  if (seatState.resources.compute > seatState.resources.energy + slack) {
    seatState.resources.compute = clamp(seatState.resources.compute - 50, 0, SCALE_MAX);
    pushLog(state, seat, {
      kind: 'upkeep',
      stringKey: null,
      deltas: { compute: -50 },
      meta: { rule: 'gridLimit' },
    });
  }

  // Cooldown expiry + hand refill (deterministic sorted order, no rng).
  for (const [id, availableTurn] of Object.entries(seatState.policy.cooldowns)) {
    if (state.turn >= availableTurn) {
      delete seatState.policy.cooldowns[id];
    }
  }
  const handSize = data.parameters.turnStructure.handSize.value;
  if (skippedLastTurn && seatState.policy.hand.length >= handSize) {
    const rotated = seatState.policy.hand[0]!;
    seatState.policy.hand = seatState.policy.hand.slice(1);
    pushLog(state, seat, {
      kind: 'upkeep',
      stringKey: null,
      deltas: null,
      meta: { rule: 'handRotation', policyId: rotated },
    });
  }
  if (seatState.policy.hand.length < handSize) {
    const unavailable = new Set([
      ...seatState.policy.hand,
      ...seatState.policy.spent,
      ...Object.keys(seatState.policy.cooldowns),
      ...(seatRules(data, seat).policyUnavailable ?? []),
    ]);
    const pool = data.policies
      .map((p) => p.id)
      .filter((id) => !unavailable.has(id))
      .sort();
    while (seatState.policy.hand.length < handSize && pool.length > 0) {
      seatState.policy.hand = [...seatState.policy.hand, pool.shift()!];
    }
  }
}

// ---------------------------------------------------------------------------
// step()
// ---------------------------------------------------------------------------

export function step(data: EngineData, prior: GameState, action: Action): GameState {
  if (prior.phase === 'ended') {
    throw new EngineError('runEnded', 'the run has ended; start a new one or replay');
  }
  if (!legalActions(prior).includes(action.type)) {
    throw new EngineError(
      'wrongPhase',
      `action '${action.type}' is illegal in phase '${prior.phase}'`,
    );
  }
  if (action.seat !== undefined && action.seat !== prior.actingSeat) {
    throw new EngineError(
      'wrongSeat',
      `action for seat '${action.seat}' while '${prior.actingSeat}' is acting`,
    );
  }
  const state = clone(prior);
  switch (action.type) {
    case 'allocate':
      handleAllocate(data, state, action);
      break;
    case 'playPolicy':
      handlePlayPolicy(data, state, action);
      break;
    case 'skipPolicy':
      handleSkipPolicy(data, state);
      break;
    case 'resolveEventChoice':
      handleResolveEvent(data, state, action);
      break;
    case 'advance':
      handleAdvance(data, state);
      break;
  }
  return state;
}

/** A run is a fold. Convenience for tests, bots and replays. */
export function runActions(data: EngineData, initial: GameState, actions: Action[]): GameState {
  return actions.reduce((state, action) => step(data, state, action), initial);
}
